name: "Licenses reuse lint"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  licenses:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1.1
